services:
  t3mt:
    image: 85423296/t3mt:test
    container_name: t3mt
    restart: unless-stopped
    ports:
      - "${TRIM_SERVICE_PORT:-8520}:80"
    volumes:
      - ${TRIM_PKGHOME}/t3mt/data:/app/backend/data
      - ${TRIM_PKGHOME}/t3mt/logs:/app/backend/logs
      - ${wizard_download_path}:/app/backend/downloads
    environment:
      - TZ=Asia/Shanghai
    security_opt:
      - apparmor:unconfined
    networks:
      - t3mt_network

networks:
  t3mt_network:
    driver: bridge
